version: '3.4'
services:  
  storageinstruments:
    build:
      context: ./services
      dockerfile: Dockerfile
    container_name: storageinstruments
    restart: on-failure
    ports:
      - "5000:80"
      
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:./services/data
    ports:
      - 9200:9200
    networks:
      - elastic
      
  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.6.2
   ports:
    - 5601:5601
   depends_on:
    - es01
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
   networks:
    - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge