version: '3.4'
services:  
  storageinstruments:
    build:
      context: ./services
      dockerfile: Dockerfile
    container_name: storageinstruments
    restart: on-failure
    ports:
      - "5000:80"